server:
  host: "0.0.0.0"
  port: "8080"
  https: true
  tls_cert: "/etc/mptcpkit/cert.pem"
  tls_key: "/etc/mptcpkit/key.pem"

api:
  script_dir: "/etc/mptcpkit/endpoints"
  key_file: "/etc/mptcpkit/keys.yml"
  dry: false
